linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 35
  maligned:
    suggest-new: true
  dupl:
    threshold: 200
  goconst:
    min-len: 2
    min-occurrences: 2
  funlen:
    lines: 150
    statements: 300

linters:
  enable-all: true
  disable:
    - maligned
    - lll
    - gochecknoinits
    - gochecknoglobals
