version: '3'
services:
  jaeger.local:
    image: jaegertracing/all-in-one
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: "9411"
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"

  prometheus.local:
    image: prom/prometheus
    ports:
      - "9090:9090"

  # dynamodb.local:
  #   image: "casualjim/dynamodb-local"
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - type: volume
  #       source: dynamodata
  #       target: /opt/dynamodb
  #       volume:
  #         nocopy: true

  s3.local:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: access-key
      MINIO_SECRET_KEY: secret-key-thing
      MINIO_BROWSER: "off"
      MINIO_DOMAIN: s3.local
    volumes:
      - type: volume
        source: miniodata
        target: /opt/minio
        volume:
          nocopy: true
    command: server /opt/minio

  app:
    image: casualjim/devenv
    user: ivan
    stdin_open: true
    tty: true
    command: /bin/zsh
    volumes:
      - ".:/home/ivan/datamon"
    depends_on:
      - prometheus.local
      # - dynamodb.local
      - s3.local
      - jaeger.local
volumes:
  dynamodata:
  miniodata:
