version: 2
jobs:
  go_build:
    working_directory: ~/project
    docker:
      - image: circleci/golang
      - image: minio/minio
        environment:
          MINIO_ACCESS_KEY: access-key
          MINIO_SECRET_KEY: secret-key-thing
          MINIO_BROWSER: "off"
          MINIO_DOMAIN: s3.local
          MINIO_HTTP_TRACE: /tmp/minio.log
        command:
          - server
          - data
    steps:
      - run:
          name: Install packages
          command: |
            sudo apt-get update
            sudo apt-get install -y git build-essential
      - run:
          name: Install go tools
          command: |
            go get -u gotest.tools/gotestsum
            mkdir -p /tmp/test-results
      - checkout
      # Restore bundle cache
      - restore_cache:
          keys:
            - pkg-cache-{{ checksum "go.sum" }}
            - pkg-cache-
      - run:
          name: Run golang tests
          command: |
            gotestsum --junitfile /tmp/test-results/go-test-report.xml ./... -- -race ./...
      - save_cache:
          key: pkg-cache-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg"
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output
      - store_test_results:
          path: /tmp/test-results
workflows:
  version: 2
  build_and_test:
    jobs:
      - go_build:
          context: "OC Common"
