apiVersion: apiextensions.k8s.io/v1beta1
description: CRD object for NATS trigger type
kind: CustomResourceDefinition
metadata:
  name: natstriggers.kubeless.io
spec:
  group: kubeless.io
  names:
    kind: NATSTrigger
    plural: natstriggers
    singular: natstrigger
  scope: Namespaced
  version: v1beta1