kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: datamon-csi-node
  namespace: datamon-csi-driver
spec:
  selector:
    matchLabels:
      app: datamon-csi-driver
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: datamon-csi-driver
    spec:
      serviceAccountName: datamon-csi-controller-sa
      hostNetwork: true
      containers:
        - name: csi-driver-registrar
          imagePullPolicy: Always
          image: quay.io/k8scsi/driver-registrar:v0.3.0
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
          #  - name: registrar-socket-dir
          #    mountPath: /var/lib/csi/sockets/
        - name: datamon-node-driver
          securityContext:
            privileged: true
          imagePullPolicy: Always
          image: gcr.io/onec-co/datamon-csi:csi
          args:
            - "--v=5"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--nodeid=$(KUBE_NODE_NAME)"
            - "--node=true"
          env:
            - name: CSI_ENDPOINT
              value: unix:/csi/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: kubelet-dir
              mountPath: /var/lib/kubelet
              mountPropagation: "Bidirectional"
            - name: plugin-dir
              mountPath: /csi
      volumes:
        # TODO(dependency): this will work when kublet registrar functionality exists
        #- name: registrar-socket-dir
        #  hostPath:
        #    path: /var/lib/kubelet/device-plugins/
        #    type: DirectoryOrCreate
        - name: kubelet-dir
          hostPath:
            path: /var/lib/kubelet
            type: Directory
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/com.google.csi.filestore/
            type: DirectoryOrCreate
