apiVersion: v1
kind: Pod
metadata:
  # This name uniquely identifies the Deployment
  name: datamon-dev
spec:
  containers:
    - name: dev
      image: golang:1.11-alpine
      tty: true
      stdin: true
      volumeMounts:
        - name: credentials
          readOnly: true
          mountPath: "/etc/datamon-creds"
  volumes:
    - name: credentials
      secret:
        secretName: gcs-credentials
    - name: datamon
      csi:
        driver: com.datamon.csi
        volumeAttributes:
          repo: ritesh-test-repo
          bundle: 1JPb0XKiMJuw4eKkrIfMxbqUWYg


