apiVersion: v1
kind: Pod
metadata:
  # This name uniquely identifies the Deployment
  name: datamon-dev
spec:
  containers:
    - name: dev
      image: golang:1.11-alpine
      tty: true
      stdin: true


