---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: ivan-goofys-alp
  name: ivan-goofys-alp
spec:
  selector:
    matchLabels:
      app: ivan-goofys-alp
  template:

    metadata:
      labels:
        app: ivan-goofys-alp
    spec:
      containers:
      - image: alpine
        imagePullPolicy: IfNotPresent
        name: alp
        stdin: true
        tty: true
        args:
        - /bin/sh
        volumeMounts:
          - name: shared
            mountPath: /mnt

      volumes:
      - name: shared
        flexVolume:
          driver: "oneconcern/flexgoofys"
          options:
            bucket: oneconcern-k8s-cluster-store
            dirMode: "0755"
            fileMode: "0644"


